[#4] Develop Connector Reference Report Goal
sentrysoftware/metricshub-connector-maven-plugin pull request #11
Opened 2024-01-02 18:38 UTC by NassimBtk

* Developed ReferenceReport that defines the `metricshub-connector-reference` Mojo.
* Developed ConnectorLibraryParser to read and parse the connectors.
* Developed ConnectorPageReferenceProducer to produce the connector page.
* Developed MainPageReferenceProducer to produce the main connector page.
* Developed PlatformReport that defines the `metricshub-connector-platforms` Mojo.
* Developed unit tests and ITs.

2024-01-03 11:21 UTC, bertysentry requested changes
Awesome! A few comments, nothing important.

2024-01-03 11:21 UTC, bertysentry commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/model/common/TechnologyType.java
> +	WMI("WMI");
`WMI/WinRM`

2024-01-03 11:21 UTC, bertysentry commented on pom.xml
In the `<reporting>` section, we can add `maven-invoker-plugin`, which will produce a [report](https://maven.apache.org/plugins/maven-invoker-plugin/report-mojo.html) as well. In this case, we'll need to move the `<version>` of `maven-invoker-plugin` to the `<pluginsManagement>` section.

2024-01-03 11:21 UTC, bertysentry commented on pom.xml
Also, in the `<reporting>` section, we can invoke the projects info reports as below, to avoid the duplicate "About" entry (which is just `index.html`):

```xml
			<!-- Default project-info-reports -->
			<plugin>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>3.5.0</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>ci-management</report>
							<report>dependencies</report>
							<report>dependency-info</report>
							<report>distribution-management</report>
							<report>issue-management</report>
							<report>licenses</report>
							<report>plugins</report>
							<report>scm</report>
							<report>summary</report>
							<report>team</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
```

This will also remove the unnecessary "Plugin management" and "Dependency Management" pages.

2024-01-03 16:21 UTC, NassimBtk commented on pom.xml
> +			<exclusions>
Indeed, they are not required. The ITs are working without the exclusions.

2024-01-03 16:25 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/Constants.java
> +	public static final String EMPTY = "";
Indeed, the constant is actually not required at all it is used only once. 🤦‍♂️

2024-01-03 16:26 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/parser/AbstractNodeProcessor.java
> +	protected abstract JsonNode doProcessing(JsonNode node) throws IOException;
Good catch, I will update this. Thakns 🙏

2024-01-03 16:27 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/parser/AbstractNodeProcessor.java
> +	 * Perform processing on the provided JsonNode and return the resulting {@link JsonNode}.
Yes, updated!

2024-01-03 16:28 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/parser/AbstractNodeProcessor.java
> +	 * Process the provided JsonNode and return the resulting {@link JsonNode}.
Yes, this sounds better. Thanks 😉

2024-01-03 16:32 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/MainPageReferenceProducer.java
> +			"This page lists the Connectors of ${project.name} ${project.version}." +
I guess that mentioning the `directory` is more preferable for you than focusing on the page itself. This makes sense, especially considering that the connectors are located within a specific directory. 👍

2024-01-03 16:38 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/PlatformReportProducer.java
> +		final String pageFilename = "platform-requirements.html";
Certainly, @bertysentry, I agree that changes might occur in the future. As we discussed, we will probably consider connector categories (tags) and attributes classification in OTEL format, particularly for `os.type` and `host.type`.

2024-01-03 16:39 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/model/common/TechnologyType.java
> +	WMI("WMI");
Sounds good!

2024-01-03 16:45 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/parser/ExtendsProcessor.java
Yes, It would be better to extract the parser in a dedicated maven project so that we simplify the plugin.

2024-01-03 16:54 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/MainPageReferenceProducer.java
> +		mainSink.text("Connector Library");
Yes, updated.

2024-01-03 16:54 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/MainPageReferenceProducer.java
> +		mainSink.text("Connector Library");
Updated as well.

2024-01-03 17:18 UTC, NassimBtk commented on pom.xml
> +			<exclusions>
Hmm, we have added these exclusions to avoid these warnings for the dependencies that need to be in the `provided` scope:
```shell
[WARNING]

Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-core:jar:3.2.5:compile
 * org.apache.maven:maven-settings:jar:3.2.5:compile
 * org.apache.maven:maven-settings-builder:jar:3.2.5:compile
 * org.apache.maven:maven-repository-metadata:jar:3.2.5:compile
 * org.apache.maven:maven-model-builder:jar:3.2.5:compile
 * org.apache.maven:maven-aether-provider:jar:3.2.5:compile
 * org.apache.maven:maven-artifact:jar:3.2.5:compile
 * org.apache.maven:maven-model:jar:3.9.6:compile
```

2024-01-03 17:27 UTC, NassimBtk commented on pom.xml
Thanks @bertysentry 😉

2024-01-03 18:21 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/ConnectorPageReferenceProducer.java
> +		sink.tableHeaderCell(SinkHelper.setClass(BOOTSTRAP_MEDIUM_4_CLASS));
Updated, the table looks better now thanks 🙏

2024-01-04 09:39 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/ConnectorPageReferenceProducer.java
> +						sink.rawText(String.format("<code class=\"language-js\">%s</code>", metricName));
Indeed, the background and colors can be changed in the final documentation.
In the integration test, I've create a `site.css` example to illustrate how to override the original `prismjs` css.

2024-01-04 09:43 UTC, NassimBtk commented on pom.xml
Yes, now, executing `mvn clean verify site` automatically generates the invoker page.
![image](https://github.com/sentrysoftware/metricshub-connector-maven-plugin/assets/14110109/1cf755f1-0e02-474c-a933-e7e308cac195)

2024-01-04 12:40 UTC, bertysentry approved these changes
Very nice!

2024-01-04 12:44 UTC, merged