Issue #59: Display the connector variables
sentrysoftware/metricshub-connector-maven-plugin pull request #61
Opened 2024-09-27 13:54 UTC by CherfaElyes

* Added a `variables` section under the `prerequisites` in the connectors pages to display the connector template variables, their description & their default value if available.
* Updated MetricsHub example content producer to add variables configuration example.
* Tested on metricshub-doc.

# Tests
## Default connector variables specified.
![image](https://github.com/user-attachments/assets/49138450-43a8-44f9-9a2a-184c59759a18)

## Default connector variables not specified (variables are present).
![image](https://github.com/user-attachments/assets/fc7ad356-e59c-491e-8449-15082485a420)

## MetricsHub.yaml example
![image](https://github.com/user-attachments/assets/6b4d5bab-9422-4ff8-93b8-6843e0c41911)

2024-09-27 15:22 UTC, bertysentry commented
I would simplify the listing of variables like below:

Variables:

* `matchCommand`: Regular expression that command line of the process must match with (default: `.*`)
* `matchName`: Regular expression that the process name must match with (default: `.*`)

So the "template" is like:

```html
<li> <code>VARNAME</code>: VARDESCRIPTION (default: <code>DEFAULTVALUE</code>)
```

Description and default value should be displayed in the doc only if they are specified, like below:

* `matchName`
* `matchName`: Regular expression that the process name must match with
* `matchName` (default: `.*`)

2024-09-27 15:23 UTC, bertysentry commented
Now an interesting question: how do we specify variable values for a connector through the CLI? 😅

2024-09-27 15:32 UTC, NassimBtk commented
There is a plan for this @bertysentry https://github.com/sentrysoftware/metricshub/issues/357

2024-09-27 16:12 UTC, NassimBtk requested changes

2024-09-27 16:12 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/ConnectorJsonNodeReader.java
> +		final Pattern pattern = Pattern.compile(variableRegex);
Create a constant please.

2024-09-27 16:12 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/maven/metricshub/connector/producer/model/common/ConnectorDefaultVariable.java
> +import lombok.AllArgsConstructor;
Should be under the ` ╱╲╱╲╱╲`  header comment.

2024-09-30 12:24 UTC, bertysentry approved these changes

2024-09-30 12:36 UTC, NassimBtk approved these changes

2024-09-30 12:36 UTC, merged